object Versions {
    const val coil = "2.4.0"
    const val navigationCompose = "2.7.1"
    const val appcompat = "1.4.0"
    const val datastore = "1.0.0"
    const val workRuntime = "2.8.1"
    const val lifecycleViewModel = "2.5.1"
    const val lifecycleRuntime = "2.5.1"
    const val pagingRuntime = "3.1.1"
    const val composeMaterial = "1.5.1"
    const val composeUITooling = "1.5.1"
    const val logbackClassic = "1.2.3"
    const val kotlinxCoroutinesCore = "1.6.4"
    const val kotlinxCoroutinesAndroid = "1.6.4"
    const val kotlin = "1.9.10"
    const val ktorClientFeatures = "1.6.4"
    const val ktorClientSerialization = "2.3.4"
    const val ktorClientCio = "2.3.4"
    const val kotlinxSerializationJson = "1.3.0"
    const val gson = "2.8.8"
    const val koinAndroid = "3.3.0"
    const val koinAndroidxCompose = "3.4.3"
    const val room = "2.6.0"
}